### **Memuat Dataset**

In [12]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("DataFiles/data_cleaning.csv")

# Ringkasan dimensi dataset
df_summary = pd.DataFrame({
    "Metrik": ["Total Baris", "Total Kolom"],
    "Nilai": [df.shape[0], df.shape[1]]
})

# Audit struktur kolom
dup_cols = df.columns[df.columns.duplicated()].tolist()
whitespace_cols = [c for c in df.columns if c != c.strip()]

df_audit = pd.DataFrame({
    "Jenis Pengecekan": ["Status Duplikasi", "Status Spasi Tersembunyi"],
    "Status": [
        "✅ Aman" if not dup_cols else "⚠️ Terdeteksi",
        "✅ Aman" if not whitespace_cols else "⚠️ Terdeteksi"
    ],
})

print("📊 RINGKASAN DATASET")
display(df_summary)

print("\n🔍 AUDIT STRUKTUR KOLOM")
display(df_audit)

print("\n👀 SAMPEL 2 DATA TERATAS")
display(df.head(2))

📊 RINGKASAN DATASET

        Metrik  Nilai
0  Total Baris  11429
1  Total Kolom     83

🔍 AUDIT STRUKTUR KOLOM

           Jenis Pengecekan  Status
0          Status Duplikasi  ✅ Aman
1  Status Spasi Tersembunyi  ✅ Aman

👀 SAMPEL 2 DATA TERATAS

,url,length_url,length_hostname,ip,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_eq,...,domain_in_title,domain_with_copyright,whois_registered_domain,domain_registration_length,domain_age,web_traffic,dns_record,google_index,page_rank,label
0,http://www.crestonwood.com/router.php,37,19,0,3,0,0,0,0,0,...,0,1,0,45,-1,0,1,1,4,0
1,http://shadetreetechnology.com/V4/validation/a...,77,23,1,1,0,0,0,0,0,...,1,0,0,77,5767,0,0,1,2,1

## **3. Split Data**

In [13]:
from sklearn.model_selection import train_test_split

# Persiapan kolom
df.columns = df.columns.str.strip()

TARGET_COL = "label"
ACTIVE_TRAIN_FEATURES = "hybrid81"  # "url37" atau "hybrid81"

url_features_37 = [
    "length_url", "length_hostname", "ip", "nb_dots", "nb_hyphens", "nb_at", "nb_qm", "nb_and",
    "nb_eq", "nb_underscore", "nb_tilde", "nb_percent", "nb_slash", "nb_star", "nb_colon",
    "nb_comma", "nb_semicolumn", "nb_dollar", "nb_space", "nb_www", "nb_com", "nb_dslash",
    "http_in_path", "https_token", "ratio_digits_url", "ratio_digits_host", "punycode", "port",
    "tld_in_path", "tld_in_subdomain", "abnormal_subdomain", "nb_subdomains", "prefix_suffix",
    "random_domain", "shortening_service", "path_extension", "nb_redirection"
]

id_cols = [c for c in ["url"] if c in df.columns]
all_features = [c for c in df.columns if c not in [TARGET_COL] + id_cols]

webcontent_features_44 = [c for c in all_features if c not in url_features_37]
hybrid_features_81 = url_features_37 + webcontent_features_44
feature_candidates = hybrid_features_81 if ACTIVE_TRAIN_FEATURES == "hybrid81" else url_features_37

# Cegah error jika ada fitur kandidat yang tidak tersedia
available_features = [c for c in feature_candidates if c in df.columns]
missing_features = [c for c in feature_candidates if c not in df.columns]
if missing_features:
    print(f"⚠️ Fitur tidak ditemukan dan diabaikan: {len(missing_features)} kolom")

# Siapkan X dan y
X_all = df[available_features].apply(pd.to_numeric, errors="coerce")
y_all = pd.to_numeric(df[TARGET_COL], errors="coerce").fillna(0).astype("int64")

# Split 80:20
X_train, X_test, y_train, y_test = train_test_split(
    X_all,
    y_all,
    test_size=0.2,
    stratify=y_all,
    random_state=12
)

# Filter fitur valid (minimal ada nilai non-NaN di train)
selected_features = X_train.columns[X_train.notna().any()].tolist()
X_train = X_train[selected_features]
X_test = X_test[selected_features]

# Imputasi median dari train
med_all = X_train.median(numeric_only=True)
X_train = X_train.fillna(med_all)
X_test = X_test.fillna(med_all)

# Output ringkasan
df_config = pd.DataFrame({
    "Pengaturan Pemodelan": [
        "Kolom Target", "Mode Pelatihan",
        "Total Kandidat Fitur", "Fitur Tersedia",
        "Jumlah Fitur Valid", "Strategi Imputasi"
    ],
    "Keterangan": [
        TARGET_COL,
        ACTIVE_TRAIN_FEATURES,
        len(feature_candidates),
        len(available_features),
        len(selected_features),
        "Median (dari Data Train)"
    ]
})

df_split = pd.DataFrame({
    "Dataset": ["Train Data (80%)", "Test Data (20%)"],
    "Jumlah Baris": [X_train.shape[0], X_test.shape[0]],
    "Jumlah Kolom (Fitur)": [X_train.shape[1], X_test.shape[1]]
})

print("⚙️ KONFIGURASI:")
display(df_config)

print("\n📊 DIMENSI DATASET:")
display(df_split)

⚙️ KONFIGURASI:

   Pengaturan Pemodelan                Keterangan
0          Kolom Target                     label
1        Mode Pelatihan                  hybrid81
2  Total Kandidat Fitur                        81
3        Fitur Tersedia                        81
4    Jumlah Fitur Valid                        81
5     Strategi Imputasi  Median (dari Data Train)

📊 DIMENSI DATASET:

            Dataset  Jumlah Baris  Jumlah Kolom (Fitur)
0  Train Data (80%)          9143                    81
1   Test Data (20%)          2286                    81

### **4. Rule-Based Filtering**

In [14]:
import re
import math
import ipaddress
from urllib.parse import urlparse
import tldextract
from sklearn.metrics import confusion_matrix
import time

SHORTENERS = {
    "bit.ly", "goo.gl", "tinyurl.com", "ow.ly", "t.co", "is.gd", "buff.ly",
    "adf.ly", "bit.do", "cutt.ly"
}
SUSPICIOUS_TLD = [
    "zip", "xyz", "top", "tk", "ga", "ml", "gq", "cf", "pw", "cc", "club",
    "ws", "biz", "online", "site", "live", "work", "icu", "info",
    "cn", "ru", "loan", "download", "click"
]
STANDARD_PORTS = {21, 22, 23, 80, 443, 445, 1433, 1521, 3306, 3389}
PHISH_HINTS = [
    "login", "verify", "update", "secure", "account", "bank",
    "paypal", "apple", "microsoft", "confirm", "signin", "password"
]
BRANDS = [
    "google", "facebook", "apple", "microsoft", "amazon", "paypal",
    "instagram", "whatsapp", "telegram", "netflix", "github", "linkedin"
]
PREFILTER_HARD_PHISHING_SCORE = 7

def entropy(s):
    if not s:
        return 0.0
    probs = [s.count(c) / len(s) for c in set(s)]
    return -sum(p * math.log2(p) for p in probs)

def parse_url(url):
    u = (url or "").strip()
    if not u.startswith(("http://", "https://")):
        u = "http://" + u
    parsed = urlparse(u)
    hostname = (parsed.hostname or "").lower()
    path = parsed.path or ""
    return u, parsed, hostname, path

def is_ip(hostname):
    try:
        ipaddress.ip_address(hostname)
        return 1
    except Exception:
        return 0

def extract_url_features(url):
    full, parsed, hostname, path = parse_url(url)
    ext = tldextract.extract(full)
    subdomain = (ext.subdomain or "").lower()
    domain = (ext.domain or "").lower()
    suffix = (ext.suffix or "").lower()

    digits_url = sum(c.isdigit() for c in full)
    digits_host = sum(c.isdigit() for c in hostname)

    random_domain = 1 if entropy(domain) > 3.5 else 0
    shortening_service = 1 if any(s in hostname for s in SHORTENERS) else 0
    prefix_suffix = 1 if "-" in domain else 0
    path_extension = 1 if "." in path.split("/")[-1] else 0
    nb_redirection = max(full.lower().count("http") - 1, 0)

    try:
        parsed_port = parsed.port
    except ValueError:
        parsed_port = None
    port_flag = 1 if (parsed_port is not None and parsed_port not in STANDARD_PORTS) else 0

    tld_last_label = suffix.split(".")[-1] if suffix else ""
    suspicious_tld_flag = 1 if (suffix in SUSPICIOUS_TLD or tld_last_label in SUSPICIOUS_TLD) else 0

    domain_in_brand = 1 if any(b in domain for b in BRANDS) else 0
    brand_in_subdomain = 1 if any(b in subdomain for b in BRANDS) else 0
    brand_in_path = 1 if any(b in path.lower() for b in BRANDS) else 0

    statistical_report = 1 if (
        suspicious_tld_flag == 1
        or is_ip(hostname) == 1
        or full.count("@") >= 1
        or random_domain == 1
    ) else 0

    return {
        "length_url": len(full),
        "length_hostname": len(hostname),
        "ip": is_ip(hostname),
        "nb_dots": full.count("."),
        "nb_hyphens": full.count("-"),
        "nb_at": full.count("@"),
        "nb_qm": full.count("?"),
        "nb_and": full.count("&"),
        "nb_eq": full.count("="),
        "nb_underscore": full.count("_"),
        "nb_tilde": full.count("~"),
        "nb_percent": full.count("%"),
        "nb_slash": full.count("/"),
        "nb_star": full.count("*"),
        "nb_colon": full.count(":"),
        "nb_comma": full.count(","),
        "nb_semicolumn": full.count(";"),
        "nb_dollar": full.count("$"),
        "nb_space": full.count(" "),
        "nb_www": 1 if "www" in hostname else 0,
        "nb_com": full.count(".com"),
        "nb_dslash": full.count("//"),
        "http_in_path": 1 if "http" in path else 0,
        "https_token": 1 if "https" in full.replace("https://", "") else 0,
        "ratio_digits_url": digits_url / max(len(full), 1),
        "ratio_digits_host": digits_host / max(len(hostname), 1),
        "punycode": 1 if "xn--" in hostname else 0,
        "port": port_flag,
        "tld_in_path": 1 if suffix and (suffix in path) else 0,
        "tld_in_subdomain": 1 if suffix and (suffix in subdomain) else 0,
        "abnormal_subdomain": 1 if ("http" in subdomain or "https" in subdomain) else 0,
        "nb_subdomains": len(subdomain.split(".")) if subdomain else 0,
        "prefix_suffix": prefix_suffix,
        "random_domain": random_domain,
        "shortening_service": shortening_service,
        "path_extension": path_extension,
        "nb_redirection": nb_redirection,
        "nb_external_redirection": 0,
        "length_words_raw": len(re.findall(r"[A-Za-z0-9]+", full.lower())),
        "char_repeat": sum(1 for i in range(1, len(full)) if full[i] == full[i - 1]),
        "shortest_words_raw": 0,
        "shortest_word_host": 0,
        "shortest_word_path": 0,
        "longest_words_raw": 0,
        "longest_word_host": 0,
        "longest_word_path": 0,
        "avg_words_raw": 0.0,
        "avg_word_host": 0.0,
        "avg_word_path": 0.0,
        "phish_hints": sum(1 for k in PHISH_HINTS if k in full.lower()),
        "domain_in_brand": domain_in_brand,
        "brand_in_subdomain": brand_in_subdomain,
        "brand_in_path": brand_in_path,
        "suspicious_tld": suspicious_tld_flag,
        "statistical_report": statistical_report,
    }

def rule_based_eval(feats):
    very_important = {
        "suspicious_tld": (feats.get("suspicious_tld", 0) == 1),
        "nb_at": (feats.get("nb_at", 0) >= 1),
        "ip": (feats.get("ip", 0) == 1),
        "nb_underscore": (feats.get("nb_underscore", 0) > 3),
    }
    important = {
        "ratio_digits_url": (feats.get("ratio_digits_url", 0) > 0.3),
        "nb_subdomains": (feats.get("nb_subdomains", 0) > 3),
        "nb_percent": (feats.get("nb_percent", 0) > 5),
        "nb_tilde": (feats.get("nb_tilde", 0) >= 1),
        "nb_semicolumn": (feats.get("nb_semicolumn", 0) >= 1),
        "nb_star": (feats.get("nb_star", 0) >= 1),
        "nb_comma": (feats.get("nb_comma", 0) >= 1),
        "random_domain": (feats.get("random_domain", 0) == 1),
    }
    less_important = {
        "length_hostname": (feats.get("length_hostname", 0) > 30),
        "nb_dollar": (feats.get("nb_dollar", 0) >= 1),
        "nb_qm": (feats.get("nb_qm", 0) > 2),
        "nb_colon": (feats.get("nb_colon", 0) > 1),
        "nb_eq": (feats.get("nb_eq", 0) > 8),
        "nb_dots": (feats.get("nb_dots", 0) > 4),
        "nb_slash": (feats.get("nb_slash", 0) > 7),
        "nb_and": (feats.get("nb_and", 0) > 3),
        "nb_hyphens": (feats.get("nb_hyphens", 0) > 3),
        "http_in_path": (feats.get("http_in_path", 0) == 1),
        "https_token": (feats.get("https_token", 0) == 1),
        "port": (feats.get("port", 0) == 1),
        "shortening_service": (feats.get("shortening_service", 0) == 1),
    }

    vi_count = sum(very_important.values())
    imp_count = sum(important.values())
    less_count = sum(less_important.values())

    risk_score = (3 * vi_count) + (2 * imp_count) + less_count
    rule_flag = int((vi_count >= 1) or (risk_score >= PREFILTER_HARD_PHISHING_SCORE))
    category = "Phishing" if rule_flag == 1 else "Suspicious"

    return risk_score, category, rule_flag, {
        "vi_count": vi_count,
        "imp_count": imp_count,
        "less_count": less_count,
    }

def predict_url(url):
    feats = extract_url_features(url)
    return rule_based_eval(feats)

# Evaluasi rule-based pada data yang sudah ada
print("Memulai evaluasi Rule-Based Model...")
t_start = time.time()

if "label" in df.columns:
    y_true = pd.to_numeric(df["label"], errors="coerce").fillna(0).astype(int)

    X_rules = df.drop(columns=["label"], errors="ignore")
    def _col(c):
        return X_rules[c] if c in X_rules.columns else pd.Series(0, index=X_rules.index)

    vi_count = (
        (_col("suspicious_tld") == 1).astype(int) +
        (_col("nb_at") >= 1).astype(int) +
        (_col("ip") == 1).astype(int) +
        (_col("nb_underscore") > 3).astype(int)
    )

    imp_count = (
        (_col("ratio_digits_url") > 0.3).astype(int) +
        (_col("nb_subdomains") > 3).astype(int) +
        (_col("nb_percent") > 5).astype(int) +
        (_col("nb_tilde") >= 1).astype(int) +
        (_col("nb_semicolumn") >= 1).astype(int) +
        (_col("nb_star") >= 1).astype(int) +
        (_col("nb_comma") >= 1).astype(int) +
        (_col("random_domain") == 1).astype(int)
    )

    less_count = (
        (_col("length_hostname") > 30).astype(int) +
        (_col("nb_dollar") >= 1).astype(int) +
        (_col("nb_qm") > 2).astype(int) +
        (_col("nb_colon") > 1).astype(int) +
        (_col("nb_eq") > 8).astype(int) +
        (_col("nb_dots") > 4).astype(int) +
        (_col("nb_slash") > 7).astype(int) +
        (_col("nb_and") > 3).astype(int) +
        (_col("nb_hyphens") > 3).astype(int) +
        (_col("http_in_path") == 1).astype(int) +
        (_col("https_token") == 1).astype(int) +
        (_col("port") == 1).astype(int) +
        (_col("shortening_service") == 1).astype(int)
    )

    risk_score = (3 * vi_count) + (2 * imp_count) + less_count
    y_pred_rule = ((vi_count >= 1) | (risk_score >= PREFILTER_HARD_PHISHING_SCORE)).astype(int)

    cm = confusion_matrix(y_true, y_pred_rule, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()

    cm_display = pd.DataFrame(
        cm,
        index=["Actual Benign (0)", "Actual Phishing (1)"],
        columns=["Benign (0)", "Phishing (1)"]
    )

    t_elapsed = time.time() - t_start
    
    
    print(f"⏳ Execution completed in{t_elapsed:.2f} detik")

Memulai evaluasi Rule-Based Model...
⏳ Execution completed in0.01 detik

## **5. Confution Matrix - Rule base**

In [15]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

if "label" in df.columns:
    # Calculate metrics
    accuracy = accuracy_score(y_true, y_pred_rule)
    precision = precision_score(y_true, y_pred_rule, zero_division=0)
    recall = recall_score(y_true, y_pred_rule, zero_division=0)
    f1 = f1_score(y_true, y_pred_rule, zero_division=0)
    
    # Try to calculate AUC if possible
    try:
        auc = roc_auc_score(y_true, y_pred_rule)
    except:
        auc = np.nan
    
    # Display confusion matrix
    print("\n🧩 CONFUSION MATRIX:")
    display(cm_display)
    
    # Display metrics (numeric values only for styling)
    metrics_data = {
        "Metrik": ["Accuracy", "Precision", "Recall", "F1 Score", "AUC"],
        "Score": [accuracy, precision, recall, f1, auc if not np.isnan(auc) else 0],
        "Persentase": [
            f"{accuracy*100:.2f}%",
            f"{precision*100:.2f}%",
            f"{recall*100:.2f}%",
            f"{f1*100:.2f}%",
            f"{auc*100:.2f}%" if not np.isnan(auc) else "N/A"
        ]
    }
    
    metrics_df = pd.DataFrame(metrics_data)
    
    print("\n📈 PERFORMANCE METRICS:")
    display(
        metrics_df.style
        .format({"Score": "{:.4f}"})
        .background_gradient(cmap="Blues", subset=["Score"])
    )
    
    # Detailed breakdown
    print("\n📋 DETAILED BREAKDOWN:")
    breakdown_data = {
        "Metrik": ["True Positives (TP)", "True Negatives (TN)", "False Positives (FP)", "False Negatives (FN)"],
        "Value": [tp, tn, fp, fn],
        "Makna": [
            "Phishing terdeteksi dengan benar ✅",
            "Benign terdeteksi dengan benar ✅",
            "Benign dianggap Phishing ❌",
            "Phishing terlewat (missed) ❌"
        ]
    }
    breakdown_df = pd.DataFrame(breakdown_data)
    display(breakdown_df)
    
    # Additional metrics
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0
    sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0
    fnr = fn / (fn + tp) if (fn + tp) > 0 else 0

🧩 CONFUSION MATRIX:

                     Benign (0)  Phishing (1)
Actual Benign (0)          5390           325
Actual Phishing (1)        3826          1888

📈 PERFORMANCE METRICS:

📋 DETAILED BREAKDOWN:

                 Metrik  Value                               Makna
0   True Positives (TP)   1888  Phishing terdeteksi dengan benar ✅
1   True Negatives (TN)   5390    Benign terdeteksi dengan benar ✅
2  False Positives (FP)    325          Benign dianggap Phishing ❌
3  False Negatives (FN)   3826        Phishing terlewat (missed) ❌

## **6. Train Model**

In [16]:
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
import time

ga_rf_params = {
    "n_estimators": 428,
    "max_depth": 16,
    "min_samples_split": 4,
    "min_samples_leaf": 1,
    "max_features": "log2",
    "random_state": 12,
    "n_jobs": -1
}

ga_xgb_params = {
    "n_estimators": 356,
    "learning_rate": 0.24470280263728614,
    "max_depth": 5,
    "subsample": 0.799109701671054,
    "colsample_bytree": 0.7933724339946145,
    "min_child_weight": 6.656725584883891,
    "gamma": 1.295747350495099,
    "reg_alpha": 0.8880322724647041,
    "reg_lambda": 2.2701556904961406,
    "eval_metric": "logloss",
    "random_state": 12,
    "n_jobs": -1
}

rf_ga = RandomForestClassifier(**ga_rf_params)
xgb_ga = XGBClassifier(**ga_xgb_params)

print("⏳ Training Random Forest (GA tuning)...")
t0 = time.time()
rf_ga.fit(X_train, y_train)
print(f"Done in {time.time()-t0:.2f}s")

print("⏳ Training XGBoost (GA tuning)...")
t0 = time.time()
xgb_ga.fit(X_train, y_train)
print(f"Done in {time.time()-t0:.2f}s")

base_learners_ga = [
    ("rf", rf_ga),
    ("xgb", xgb_ga),
]
meta_learner_ga = LogisticRegression(max_iter=1000, class_weight="balanced", random_state=12)

stack_ga = StackingClassifier(
    estimators=base_learners_ga,
    final_estimator=meta_learner_ga,
    stack_method="predict_proba",
    n_jobs=-1
)

print("⏳ Training Stacking (GA tuning)...")
t0 = time.time()
stack_ga.fit(X_train, y_train)
print(f"Done in {time.time()-t0:.2f}s")

⏳ Training Random Forest (GA tuning)...
Done in 1.64s
⏳ Training XGBoost (GA tuning)...
Done in 0.71s
⏳ Training Stacking (GA tuning)...
Done in 20.04s

## **7. Confution Matrix**

In [17]:
import pandas as pd
import numpy as np
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix
)

def evaluate_model(name, model, X_eval, y_eval):
    y_pred = model.predict(X_eval)
    y_prob = model.predict_proba(X_eval)[:, 1] if hasattr(model, "predict_proba") else y_pred

    tn, fp, fn, tp = confusion_matrix(y_eval, y_pred, labels=[0, 1]).ravel()

    try:
        auc = roc_auc_score(y_eval, y_prob)
    except Exception:
        auc = np.nan

    cm_table = pd.DataFrame(
        confusion_matrix(y_eval, y_pred, labels=[0, 1]),
        index=["Actual Benign (0)", "Actual Phishing (1)"],
        columns=["Benign (0)", "Phishing (1)"]
    )

    return {
        "Model": name,
        "Accuracy": accuracy_score(y_eval, y_pred),
        "Precision": precision_score(y_eval, y_pred, zero_division=0),
        "Recall": recall_score(y_eval, y_pred, zero_division=0),
        "F1 Score": f1_score(y_eval, y_pred, zero_division=0),
        "AUC": auc,
        "✅ TP": int(tp),
        "✅ TN": int(tn),
        "❌ FP": int(fp),
        "❌ FN": int(fn),
        "cm_table": cm_table
    }

evaluations = [
    evaluate_model("Random Forest (GA)", rf_ga, X_test, y_test),
    evaluate_model("XGBoost (GA)", xgb_ga, X_test, y_test),
    evaluate_model("Stacking (RF+XGB+LR, GA)", stack_ga, X_test, y_test),
]

# Leaderboard metrik
detail_df = pd.DataFrame([{k: v for k, v in e.items() if k != "cm_table"} for e in evaluations])

print("📊 PERBANDINGAN PERFORMA MODEL PADA DATA TEST")
display(
    detail_df.style
    .format({
        "Accuracy": "{:.3f}",
        "Precision": "{:.3f}",
        "Recall": "{:.3f}",
        "F1 Score": "{:.3f}",
        "AUC": "{:.3f}"
    })
    .background_gradient(cmap="Greens", subset=["Accuracy", "Precision", "Recall", "F1 Score", "AUC"])
    .background_gradient(cmap="Blues", subset=["✅ TP", "✅ TN"])
    .background_gradient(cmap="Reds", subset=["❌ FP", "❌ FN"])
    .set_properties(**{"text-align": "center", "vertical-align": "middle"})
)

# Confusion matrix per model
for e in evaluations:
    print(f"\n🧩 CONFUSION MATRIX - {e['Model']}")
    display(e["cm_table"])

📊 PERBANDINGAN PERFORMA MODEL PADA DATA TEST

🧩 CONFUSION MATRIX - Random Forest (GA)

                     Benign (0)  Phishing (1)
Actual Benign (0)          1111            32
Actual Phishing (1)          32          1111

🧩 CONFUSION MATRIX - XGBoost (GA)

                     Benign (0)  Phishing (1)
Actual Benign (0)          1115            28
Actual Phishing (1)          29          1114

🧩 CONFUSION MATRIX - Stacking (RF+XGB+LR, GA)

                     Benign (0)  Phishing (1)
Actual Benign (0)          1112            31
Actual Phishing (1)          30          1113

# 8. Perbandingan Hybrid Models

In [18]:
import time
import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix
)

# ─── Fungsi rule-based dari fitur DataFrame (vectorized) ─────────────────────
def rule_based_from_df(X_df):
    """
    Menerapkan rule-based scoring secara vectorized.
    Mengembalikan:
      y_pred_rule   : array prediksi (0/1)
      mask_to_ml    : boolean mask — True = lolos filter → diteruskan ke ML
    """
    def col(c):
        return X_df[c] if c in X_df.columns else pd.Series(0, index=X_df.index)

    vi_count = (
        (col('suspicious_tld') == 1).astype(int) +
        (col('nb_at')          >= 1).astype(int) +
        (col('ip')             == 1).astype(int) +
        (col('nb_underscore')  >  3).astype(int)
    )
    imp_count = (
        (col('ratio_digits_url') > 0.3).astype(int) +
        (col('nb_subdomains')    >  3 ).astype(int) +
        (col('nb_percent')       >  5 ).astype(int) +
        (col('nb_tilde')         >= 1 ).astype(int) +
        (col('nb_semicolumn')    >= 1 ).astype(int) +
        (col('nb_star')          >= 1 ).astype(int) +
        (col('nb_comma')         >= 1 ).astype(int) +
        (col('random_domain')    == 1 ).astype(int)
    )
    less_count = (
        (col('length_hostname')    >  30).astype(int) +
        (col('nb_dollar')          >= 1 ).astype(int) +
        (col('nb_qm')              >  2 ).astype(int) +
        (col('nb_colon')           >  1 ).astype(int) +
        (col('nb_eq')              >  8 ).astype(int) +
        (col('nb_dots')            >  4 ).astype(int) +
        (col('nb_slash')           >  7 ).astype(int) +
        (col('nb_and')             >  3 ).astype(int) +
        (col('nb_hyphens')         >  3 ).astype(int) +
        (col('http_in_path')       == 1 ).astype(int) +
        (col('https_token')        == 1 ).astype(int) +
        (col('port')               == 1 ).astype(int) +
        (col('shortening_service') == 1 ).astype(int)
    )

    risk_score  = (3 * vi_count) + (2 * imp_count) + less_count
    rule_flag   = ((vi_count >= 1) | (risk_score >= PREFILTER_HARD_PHISHING_SCORE))
    y_pred_rule = rule_flag.astype(int)
    mask_to_ml  = ~rule_flag   # True = tidak tertangkap rule → lanjut ke ML

    return y_pred_rule.values, mask_to_ml.values


# ─── Siapkan X full dataset ───────────────────────────────────────────────────
X_full = df[selected_features].apply(pd.to_numeric, errors='coerce').fillna(med_all)
y_full = pd.to_numeric(df[TARGET_COL], errors='coerce').fillna(0).astype(int)
total_url = len(y_full)


# ─── Jalankan Hybrid (full dataset) ──────────────────────────────────────────
print('=' * 65)
print('🔀 MODEL 4 — RULE-BASED FILTERING + STACKING (HYBRID)')
print('=' * 65)

t0_hybrid = time.perf_counter()

# Langkah 1: Rule-based filter pada seluruh dataset
y_rule_full, mask_to_ml_full = rule_based_from_df(X_full)
n_rule_decided = int((~mask_to_ml_full).sum())
n_passed_to_ml = int(mask_to_ml_full.sum())

# Langkah 2: ML Stacking hanya untuk URL yang lolos filter
final_pred_full = y_rule_full.copy()
if n_passed_to_ml > 0:
    X_for_ml  = X_full[mask_to_ml_full]
    ml_pred   = stack_ga.predict(X_for_ml)
    final_pred_full[mask_to_ml_full] = ml_pred

t_hybrid_full = time.perf_counter() - t0_hybrid

# ─── Tampilkan distribusi beban ───────────────────────────────────────────────
pct_rule = (n_rule_decided / total_url) * 100
pct_ml   = (n_passed_to_ml  / total_url) * 100

dist_df = pd.DataFrame({
    'Lapisan': ['Rule-Based Filter', 'ML Stacking', 'Total'],
    'Jumlah URL': [n_rule_decided, n_passed_to_ml, total_url],
    'Persentase': [f'{pct_rule:.1f}%', f'{pct_ml:.1f}%', '100%'],
    'Keterangan': [
        'Langsung diklasifikasi oleh rule',
        'Diteruskan ke model ML',
        'Seluruh dataset'
    ]
})

print(f'\n📦 DISTRIBUSI BEBAN KERJA (Full Dataset = {total_url:,} URL)')
display(dist_df.style.set_properties(**{'text-align': 'center'}))
print(f'\n⏱️  Total execution time Hybrid (full dataset): {t_hybrid_full:.4f} detik')


# ─── Evaluasi Hybrid pada Test Set (apple-to-apple) ──────────────────────────
print('\n' + '=' * 65)
print('📊 EVALUASI HYBRID PADA DATA TEST')
print('=' * 65)

t0_test = time.perf_counter()

y_rule_test, mask_to_ml_test = rule_based_from_df(X_test)
final_pred_test = y_rule_test.copy()
if mask_to_ml_test.sum() > 0:
    ml_pred_test = stack_ga.predict(X_test[mask_to_ml_test])
    final_pred_test[mask_to_ml_test] = ml_pred_test

t_hybrid_test = time.perf_counter() - t0_test

# Confusion matrix Hybrid
cm_hybrid = confusion_matrix(y_test, final_pred_test, labels=[0, 1])
tn_h, fp_h, fn_h, tp_h = cm_hybrid.ravel()
cm_hybrid_df = pd.DataFrame(
    cm_hybrid,
    index=['Actual Benign (0)', 'Actual Phishing (1)'],
    columns=['Benign (0)', 'Phishing (1)']
)

print('\n🧩 CONFUSION MATRIX - Rule-Based + Stacking (Hybrid)')
display(cm_hybrid_df)

acc_h  = accuracy_score(y_test, final_pred_test)
prec_h = precision_score(y_test, final_pred_test, zero_division=0)
rec_h  = recall_score(y_test, final_pred_test, zero_division=0)
f1_h   = f1_score(y_test, final_pred_test, zero_division=0)
try:
    prob_test = stack_ga.predict_proba(X_test)[:, 1]
    auc_h = roc_auc_score(y_test, np.where(mask_to_ml_test, prob_test, y_rule_test.astype(float)))
except:
    auc_h = np.nan

metrics_hybrid = pd.DataFrame({
    'Metrik': ['Accuracy', 'Precision', 'Recall', 'F1 Score', 'AUC'],
    'Score':  [acc_h, prec_h, rec_h, f1_h, auc_h if not np.isnan(auc_h) else 0],
    'Persentase': [
        f'{acc_h*100:.2f}%', f'{prec_h*100:.2f}%', f'{rec_h*100:.2f}%',
        f'{f1_h*100:.2f}%',
        f'{auc_h*100:.2f}%' if not np.isnan(auc_h) else 'N/A'
    ]
})

print('\n📈 PERFORMANCE METRICS - Hybrid')
display(
    metrics_hybrid.style
    .format({'Score': '{:.4f}'})
    .background_gradient(cmap='Blues', subset=['Score'])
)

breakdown_hybrid = pd.DataFrame({
    'Metrik': ['True Positives (TP)', 'True Negatives (TN)', 'False Positives (FP)', 'False Negatives (FN)'],
    'Value':  [tp_h, tn_h, fp_h, fn_h],
    'Makna':  [
        'Phishing terdeteksi dengan benar ✅',
        'Benign terdeteksi dengan benar ✅',
        'Benign dianggap Phishing ❌',
        'Phishing terlewat (missed) ❌'
    ]
})

print('\n📋 DETAILED BREAKDOWN - Hybrid')
display(breakdown_hybrid)

print(f'\n⏱️  Inference time Hybrid (test set): {t_hybrid_test*1000:.2f} ms')

=================================================================
🔀 MODEL 4 — RULE-BASED FILTERING + STACKING (HYBRID)
=================================================================

📦 DISTRIBUSI BEBAN KERJA (Full Dataset = 11,429 URL)

⏱️  Total execution time Hybrid (full dataset): 0.3486 detik

=================================================================
📊 EVALUASI HYBRID PADA DATA TEST
=================================================================

🧩 CONFUSION MATRIX - Rule-Based + Stacking (Hybrid)

                     Benign (0)  Phishing (1)
Actual Benign (0)          1061            82
Actual Phishing (1)          29          1114

📈 PERFORMANCE METRICS - Hybrid

📋 DETAILED BREAKDOWN - Hybrid

                 Metrik  Value                               Makna
0   True Positives (TP)   1114  Phishing terdeteksi dengan benar ✅
1   True Negatives (TN)   1061    Benign terdeteksi dengan benar ✅
2  False Positives (FP)     82          Benign dianggap Phishing ❌
3  False Negatives (FN)     29        Phishing terlewat (missed) ❌

⏱️  Inference time Hybrid (test set): 196.39 ms

In [19]:
import pandas as pd
import numpy as np
import time
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix
)

# ─── Fungsi untuk mengukur latency inference per model ─────────────────────────
def measure_inference_latency(model, X_test, iterations=10):
    """Mengukur latency inference dalam milidetik (rata-rata dari beberapa iterasi)"""
    times = []
    for _ in range(iterations):
        t0 = time.perf_counter()
        _ = model.predict(X_test)
        t1 = time.perf_counter()
        times.append((t1 - t0) * 1000)  # Convert to ms
    return {
        'mean_ms': np.mean(times),
        'min_ms': np.min(times),
        'max_ms': np.max(times),
        'std_ms': np.std(times)
    }

# ─── Kumpulkan informasi dari ke-4 model ──────────────────────────────────────

# Model 1: Random Forest (GA)
print('⏳ Measuring latency for Random Forest...')
latency_rf = measure_inference_latency(rf_ga, X_test)
y_pred_rf = rf_ga.predict(X_test)
cm_rf = confusion_matrix(y_test, y_pred_rf, labels=[0, 1])
tn_rf, fp_rf, fn_rf, tp_rf = cm_rf.ravel()
try:
    prob_rf = rf_ga.predict_proba(X_test)[:, 1]
    auc_rf = roc_auc_score(y_test, prob_rf)
except:
    auc_rf = np.nan

model_1 = {
    'Model': 'Random Forest (GA)',
    'Accuracy': accuracy_score(y_test, y_pred_rf),
    'Precision': precision_score(y_test, y_pred_rf, zero_division=0),
    'Recall': recall_score(y_test, y_pred_rf, zero_division=0),
    'F1 Score': f1_score(y_test, y_pred_rf, zero_division=0),
    'AUC': auc_rf if not np.isnan(auc_rf) else 0,
    'TP': int(tp_rf),
    'TN': int(tn_rf),
    'FP': int(fp_rf),
    'FN': int(fn_rf),
    'Execution Time (s)': 'Training phase',
    'Inference Latency (ms)': f"{latency_rf['mean_ms']:.3f} ± {latency_rf['std_ms']:.3f}",
    'Min Latency (ms)': f"{latency_rf['min_ms']:.3f}",
    'Max Latency (ms)': f"{latency_rf['max_ms']:.3f}"
}

# Model 2: XGBoost (GA)
print('⏳ Measuring latency for XGBoost...')
latency_xgb = measure_inference_latency(xgb_ga, X_test)
y_pred_xgb = xgb_ga.predict(X_test)
cm_xgb = confusion_matrix(y_test, y_pred_xgb, labels=[0, 1])
tn_xgb, fp_xgb, fn_xgb, tp_xgb = cm_xgb.ravel()
try:
    prob_xgb = xgb_ga.predict_proba(X_test)[:, 1]
    auc_xgb = roc_auc_score(y_test, prob_xgb)
except:
    auc_xgb = np.nan

model_2 = {
    'Model': 'XGBoost (GA)',
    'Accuracy': accuracy_score(y_test, y_pred_xgb),
    'Precision': precision_score(y_test, y_pred_xgb, zero_division=0),
    'Recall': recall_score(y_test, y_pred_xgb, zero_division=0),
    'F1 Score': f1_score(y_test, y_pred_xgb, zero_division=0),
    'AUC': auc_xgb if not np.isnan(auc_xgb) else 0,
    'TP': int(tp_xgb),
    'TN': int(tn_xgb),
    'FP': int(fp_xgb),
    'FN': int(fn_xgb),
    'Execution Time (s)': 'Training phase',
    'Inference Latency (ms)': f"{latency_xgb['mean_ms']:.3f} ± {latency_xgb['std_ms']:.3f}",
    'Min Latency (ms)': f"{latency_xgb['min_ms']:.3f}",
    'Max Latency (ms)': f"{latency_xgb['max_ms']:.3f}"
}

# Model 3: Stacking (RF+XGB+LR)
print('⏳ Measuring latency for Stacking...')
latency_stack = measure_inference_latency(stack_ga, X_test)
y_pred_stack = stack_ga.predict(X_test)
cm_stack = confusion_matrix(y_test, y_pred_stack, labels=[0, 1])
tn_stack, fp_stack, fn_stack, tp_stack = cm_stack.ravel()
try:
    prob_stack = stack_ga.predict_proba(X_test)[:, 1]
    auc_stack = roc_auc_score(y_test, prob_stack)
except:
    auc_stack = np.nan

model_3 = {
    'Model': 'Stacking (RF+XGB+LR, GA)',
    'Accuracy': accuracy_score(y_test, y_pred_stack),
    'Precision': precision_score(y_test, y_pred_stack, zero_division=0),
    'Recall': recall_score(y_test, y_pred_stack, zero_division=0),
    'F1 Score': f1_score(y_test, y_pred_stack, zero_division=0),
    'AUC': auc_stack if not np.isnan(auc_stack) else 0,
    'TP': int(tp_stack),
    'TN': int(tn_stack),
    'FP': int(fp_stack),
    'FN': int(fn_stack),
    'Execution Time (s)': 'Training phase',
    'Inference Latency (ms)': f"{latency_stack['mean_ms']:.3f} ± {latency_stack['std_ms']:.3f}",
    'Min Latency (ms)': f"{latency_stack['min_ms']:.3f}",
    'Max Latency (ms)': f"{latency_stack['max_ms']:.3f}"
}

# Model 4: Hybrid (Rule-Based + Stacking)
print('⏳ Measuring latency for Hybrid...')

# Calculate Hybrid latency manually dengan rule+stack
def hybrid_predict(X):
    y_rule, mask_to_ml = rule_based_from_df(X)
    pred = y_rule.copy()
    if mask_to_ml.sum() > 0:
        pred[mask_to_ml] = stack_ga.predict(X[mask_to_ml])
    return pred

hybrid_times = []
for _ in range(10):
    t0 = time.perf_counter()
    _ = hybrid_predict(X_test)
    t1 = time.perf_counter()
    hybrid_times.append((t1 - t0) * 1000)

latency_hybrid = {
    'mean_ms': np.mean(hybrid_times),
    'min_ms': np.min(hybrid_times),
    'max_ms': np.max(hybrid_times),
    'std_ms': np.std(hybrid_times)
}

cm_hybrid_full = confusion_matrix(y_test, final_pred_test, labels=[0, 1])
tn_hybrid_full, fp_hybrid_full, fn_hybrid_full, tp_hybrid_full = cm_hybrid_full.ravel()
try:
    prob_hybrid = np.where(mask_to_ml_test, stack_ga.predict_proba(X_test)[:, 1], 
                           final_pred_test.astype(float))
    auc_hybrid = roc_auc_score(y_test, prob_hybrid)
except:
    auc_hybrid = np.nan

model_4 = {
    'Model': 'Hybrid (Rule+Stacking)',
    'Accuracy': accuracy_score(y_test, final_pred_test),
    'Precision': precision_score(y_test, final_pred_test, zero_division=0),
    'Recall': recall_score(y_test, final_pred_test, zero_division=0),
    'F1 Score': f1_score(y_test, final_pred_test, zero_division=0),
    'AUC': auc_hybrid if not np.isnan(auc_hybrid) else 0,
    'TP': int(tp_hybrid_full),
    'TN': int(tn_hybrid_full),
    'FP': int(fp_hybrid_full),
    'FN': int(fn_hybrid_full),
    'Execution Time (s)': f"{t_hybrid_test:.4f}",
    'Inference Latency (ms)': f"{latency_hybrid['mean_ms']:.3f} ± {latency_hybrid['std_ms']:.3f}",
    'Min Latency (ms)': f"{latency_hybrid['min_ms']:.3f}",
    'Max Latency (ms)': f"{latency_hybrid['max_ms']:.3f}"
}

# ─── Gabungkan semua model dalam satu DataFrame ───────────────────────────────
all_models = [model_1, model_2, model_3, model_4]

# 1. Comparison Table (Performance Metrics)
print('\n' + '='*95)
print('📊 PERBANDINGAN 4 MODEL - PERFORMANCE METRICS')
print('='*95)

comparison_df = pd.DataFrame([
    {
        'Model': m['Model'],
        'Accuracy': m['Accuracy'],
        'Precision': m['Precision'],
        'Recall': m['Recall'],
        'F1 Score': m['F1 Score'],
        'AUC': m['AUC'],
    }
    for m in all_models
])

display(
    comparison_df.style
    .format({
        'Accuracy': '{:.4f}',
        'Precision': '{:.4f}',
        'Recall': '{:.4f}',
        'F1 Score': '{:.4f}',
        'AUC': '{:.4f}'
    })
    .background_gradient(cmap='RdYlGn', subset=['Accuracy', 'Precision', 'Recall', 'F1 Score', 'AUC'])
    .set_properties(**{'text-align': 'center'})
)

# 2. Confusion Matrix Comparison
print('\n' + '='*95)
print('🧩 CONFUSION MATRIX - KESELURUHAN 4 MODEL')
print('='*95)

cm_comparison_df = pd.DataFrame([
    {
        'Model': m['Model'],
        'TP ✅': m['TP'],
        'TN ✅': m['TN'],
        'FP ❌': m['FP'],
        'FN ❌': m['FN'],
    }
    for m in all_models
])

display(
    cm_comparison_df.style
    .background_gradient(cmap='Greens', subset=['TP ✅', 'TN ✅'])
    .background_gradient(cmap='Reds', subset=['FP ❌', 'FN ❌'])
    .set_properties(**{'text-align': 'center'})
)

# 3. Execution Time & Latency Comparison
print('\n' + '='*95)
print('⏱️  EXECUTION TIME DAN LATENCY COMPARISON')
print('='*95)

latency_comparison_df = pd.DataFrame([
    {
        'Model': m['Model'],
        'Execution Time': m['Execution Time (s)'],
        'Mean Latency (ms)': m['Inference Latency (ms)'],
        'Min Latency (ms)': m['Min Latency (ms)'],
        'Max Latency (ms)': m['Max Latency (ms)']
    }
    for m in all_models
])

display(
    latency_comparison_df.style
    .set_properties(**{'text-align': 'center'})
)

print('\n✅ Perbandingan ke-4 model selesai!')

⏳ Measuring latency for Random Forest...
⏳ Measuring latency for XGBoost...
⏳ Measuring latency for Stacking...
⏳ Measuring latency for Hybrid...

===============================================================================================
📊 PERBANDINGAN 4 MODEL - PERFORMANCE METRICS
===============================================================================================

===============================================================================================
🧩 CONFUSION MATRIX - KESELURUHAN 4 MODEL
===============================================================================================

===============================================================================================
⏱️  EXECUTION TIME DAN LATENCY COMPARISON
===============================================================================================

✅ Perbandingan ke-4 model selesai!

# 9. Execution Time

In [20]:
print('\n' + '='*95)
print('🎯 ANALISIS PENGHEMATAN WAKTU: RULE-BASED FILTERING DALAM HYBRID MODEL')
print('='*95)

# Extract latency values from the measured data
stacking_latency = latency_stack['mean_ms']
hybrid_latency = latency_hybrid['mean_ms']

# Calculate time saved (untuk referensi, tapi fokus di full dataset)
time_saved_ms = stacking_latency - hybrid_latency
time_saved_pct = (time_saved_ms / stacking_latency) * 100

# ─── ANALISIS FULL DATASET (YANG UTAMA) ─────────────────────────────────────
print('\n📌 ANALISIS FULL DATASET (Training + Test)')
total_samples_full = len(X_full)
rule_decided_full = n_rule_decided  # Dari cell sebelumnya
ml_processed_full = n_passed_to_ml
pct_rule_decided_full = (rule_decided_full / total_samples_full) * 100
pct_ml_processed_full = (ml_processed_full / total_samples_full) * 100

# Estimasi waktu jika full dataset dijalankan dengan Stacking pure
estimated_stacking_time_full = stacking_latency * (total_samples_full / len(X_test))
estimated_hybrid_time_full = t_hybrid_full * 1000  # Convert to ms

analysis_data_full = {
    'Metrik': [
        'Total Samples',
        'Diputuskan oleh Rule-Based',
        'Diproses oleh Stacking',
        '',
        'Est. Pure Stacking Time',
        'Actual Hybrid Time',
        'Waktu Dihemat',
        'Persentase Penghematan'
    ],
    'Nilai': [
        f'{total_samples_full:,}',
        f'{int(rule_decided_full):,} ({pct_rule_decided_full:.1f}%)',
        f'{int(ml_processed_full):,} ({pct_ml_processed_full:.1f}%)',
        '',
        f'{estimated_stacking_time_full:.2f} ms',
        f'{estimated_hybrid_time_full:.2f} ms',
        f'{estimated_stacking_time_full - estimated_hybrid_time_full:.2f} ms',
        f'{((estimated_stacking_time_full - estimated_hybrid_time_full) / estimated_stacking_time_full * 100):.1f}%'
    ],
    'Keterangan': [
        'Seluruh dataset',
        'Tertangkap rule → skip ML',
        'Perlu inference ML',
        '',
        'Estimasi jika non-hybrid',
        'Waktu aktual hybrid',
        'Penghematan keseluruhan',
        'Efisiensi peningkatan'
    ]
}

analysis_df_full = pd.DataFrame(analysis_data_full)
print('\n📋 DETAIL ANALISIS:')
display(
    analysis_df_full.style
    .set_properties(**{'text-align': 'left', 'white-space': 'pre-wrap'})
)

# ─── EFFICIENCY CALCULATION ────────────────────────────────────────────────
print('\n📊 EFISIENSI DETAIL (FULL DATASET):')
if ml_processed_full > 0:
    stacking_workload_reduction_full = (rule_decided_full / total_samples_full) * 100
    time_saved_full = estimated_stacking_time_full - estimated_hybrid_time_full
    time_saved_pct_full = (time_saved_full / estimated_stacking_time_full) * 100
    avg_latency_per_sample_pure = estimated_stacking_time_full / total_samples_full
    avg_latency_per_sample_hybrid = estimated_hybrid_time_full / total_samples_full
    
    print(f'├─ Rule-Based mengurangi beban Stacking: {stacking_workload_reduction_full:.1f}%')
    print(f'├─ Latency per sample (Pure Stacking): {avg_latency_per_sample_pure:.4f} ms/sample')
    print(f'├─ Latency per sample (Hybrid): {avg_latency_per_sample_hybrid:.4f} ms/sample')
    print(f'├─ Total waktu hemat: {time_saved_full:.2f} ms ({time_saved_pct_full:.1f}%)')
    print(f'└─ Akselerasi keseluruhan: {estimated_stacking_time_full/estimated_hybrid_time_full:.2f}x lebih cepat' if estimated_hybrid_time_full > 0 else '└─ Akselerasi: N/A')

# ─── SUMMARY INSIGHTS (FULL DATASET) ───────────────────────────────────────
print('\n💡 KESIMPULAN:')
time_saved_full = estimated_stacking_time_full - estimated_hybrid_time_full
time_saved_pct_full = (time_saved_full / estimated_stacking_time_full) * 100

if time_saved_pct_full > 0:
    print(f'✅ Rule-Based Filter MEMBANTU SIGNIFIKAN!\n')
    print(f'   📊 RINGKASAN HASIL:')
    print(f'   • Total dataset: {total_samples_full:,} URLs')
    print(f'   • Rule-Based menangani: {pct_rule_decided_full:.1f}% sample (langsung tanpa ML)')
    print(f'   • Stacking memproses: {pct_ml_processed_full:.1f}% sample saja')
    print(f'   • Hemat waktu eksekusi: {time_saved_full:.2f} ms ({time_saved_pct_full:.1f}%)')
    print(f'   • Kecepatan: {estimated_stacking_time_full/estimated_hybrid_time_full:.2f}x lebih cepat')
    
    if time_saved_pct_full > 40:
        print(f'\n   🚀 PENGHEMATAN SANGAT SIGNIFIKAN! Hybrid sangat efisien untuk dataset besar!')
    elif time_saved_pct_full > 20:
        print(f'\n   ⚡ Penghematan baik! Rule-Based filter terbukti efektif!')
    else:
        print(f'\n   ✓ Penghematan cukup. Rule-Based memberikan kontribusi positif.')
else:
    print(f'⚠️  Rule-Based Filter menambah overhead!\n')
    print(f'   • Latency Hybrid lebih lama: {abs(time_saved_full):.2f} ms')
    print(f'   • Rekomendasi: pertimbangkan optimisasi rule-based rules')

print('\n' + '='*95)

===============================================================================================
🎯 ANALISIS PENGHEMATAN WAKTU: RULE-BASED FILTERING DALAM HYBRID MODEL
===============================================================================================

📌 ANALISIS FULL DATASET (Training + Test)

📋 DETAIL ANALISIS:

📊 EFISIENSI DETAIL (FULL DATASET):
├─ Rule-Based mengurangi beban Stacking: 19.4%
├─ Latency per sample (Pure Stacking): 0.0823 ms/sample
├─ Latency per sample (Hybrid): 0.0305 ms/sample
├─ Total waktu hemat: 592.42 ms (63.0%)
└─ Akselerasi keseluruhan: 2.70x lebih cepat

💡 KESIMPULAN:
✅ Rule-Based Filter MEMBANTU SIGNIFIKAN!

   📊 RINGKASAN HASIL:
   • Total dataset: 11,429 URLs
   • Rule-Based menangani: 19.4% sample (langsung tanpa ML)
   • Stacking memproses: 80.6% sample saja
   • Hemat waktu eksekusi: 592.42 ms (63.0%)
   • Kecepatan: 2.70x lebih cepat

   🚀 PENGHEMATAN SANGAT SIGNIFIKAN! Hybrid sangat efisien untuk dataset besar!

===============================================================================================